### ISSUE TITLE
Cannot install HandbrakeCLI in a Docker container

### ISSUE THREAD

**Issue by pooshonbanerjee** [75lb/handbrake-js#75]
### Preface

- I need to run a node.js application from a PaaS deployment.
- This application would require to encode videos using HandbrakeCLI.
- Since the application would be running from a managed platform, there is no question of getting into the server and installing anything, hence comes Docker.
- But no matter what I try, I cannot get HandbrakeCLI to install.
- Please note that I had to add `apt-get install -y software-properties-common` command, since `apt-add-repository` wouldn't work without it.

### Dockerfile

```
# Use an official Node.js runtime as a parent image
FROM ubuntu


# Install Handbrake-CLI

RUN apt-get update && \
    apt-get install -y software-properties-common && \
    add-apt-repository --yes ppa:stebbins/handbrake-releases && \
    apt-get install -y handbrake-cli

# Set the working directory to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install any needed packages specified in package.json
RUN npm install

# Make port 3000 available to the world outside this container
EXPOSE 3000

# Define environment variable
# ENV NODE_ENV=production

# Run the app when the container launches
CMD ["npm", "start"]
```
### Errors

- I have got several, all kinds. The most recent one is this.
```
[+] Building 106.1s (7/10)                                                                                                                                             
 => [internal] load build definition from Dockerfile                                                                                                              0.0s
 => => transferring dockerfile: 760B                                                                                                                              0.0s
 => [internal] load .dockerignore                                                                                                                                 0.0s
 => => transferring context: 2B                                                                                                                                   0.0s
 => [internal] load metadata for docker.io/library/ubuntu:latest                                                                                                  1.1s
 => [internal] load build context                                                                                                                                 0.1s
 => => transferring context: 214.03kB                                                                                                                             0.1s
 => CACHED [1/6] FROM docker.io/library/ubuntu@sha256:6120be6a2b7ce665d0cbddc3ce6eae60fe94637c6a66985312d1f02f63cc0bcd                                            0.0s
 => [2/6] RUN apt-get update &&     apt-get install -y software-properties-common                                                                               102.2s
 => ERROR [3/6] RUN add-apt-repository --yes ppa:stebbins/handbrake-releases                                                                                      2.8s
------                                                                                                                                                                 
 > [3/6] RUN add-apt-repository --yes ppa:stebbins/handbrake-releases:                                                                                                 
#6 2.674 PPA publishes dbgsym, you may need to include 'main/debug' component                                                                                          
#6 2.674 Repository: 'deb https://ppa.launchpadcontent.net/stebbins/handbrake-releases/ubuntu/ jammy main'                                                             
#6 2.674 Description:                                                                                                                                                  
#6 2.674 tag:launchpad.net:2008:redacted                                                                                                                               
#6 2.674 More info: https://launchpad.net/~stebbins/+archive/ubuntu/handbrake-releases
#6 2.674 Adding repository.
#6 2.674 Adding deb entry to /etc/apt/sources.list.d/stebbins-ubuntu-handbrake-releases-jammy.list
#6 2.674 Adding disabled deb-src entry to /etc/apt/sources.list.d/stebbins-ubuntu-handbrake-releases-jammy.list
#6 2.681 Traceback (most recent call last):
#6 2.681   File "/usr/bin/add-apt-repository", line 364, in <module>
#6 2.681     sys.exit(0 if addaptrepo.main() else 1)
#6 2.681   File "/usr/bin/add-apt-repository", line 357, in main
#6 2.681     shortcut.add()
#6 2.681   File "/usr/lib/python3/dist-packages/softwareproperties/shortcuthandler.py", line 222, in add
#6 2.681     self.add_key()
#6 2.681   File "/usr/lib/python3/dist-packages/softwareproperties/shortcuthandler.py", line 398, in add_key
#6 2.681     if not all((self.trustedparts_file, self.trustedparts_content)):
#6 2.681   File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 141, in trustedparts_content
#6 2.681     key = self.lpppa.getSigningKeyData()
#6 2.681   File "/usr/lib/python3/dist-packages/lazr/restfulclient/resource.py", line 592, in __call__
#6 2.681     response, content = self.root._browser._request(
#6 2.681   File "/usr/lib/python3/dist-packages/lazr/restfulclient/_browser.py", line 429, in _request
#6 2.681     raise error
#6 2.681 lazr.restfulclient.errors.Unauthorized: HTTP Error 401: Unauthorized
#6 2.681 Response headers:
#6 2.681 ---
#6 2.681 content-length: 67
#6 2.681 content-security-policy: frame-ancestors 'self';
#6 2.681 content-type: text/plain;charset=utf-8
#6 2.681 date: Wed, 21 Jun 2023 08:41:25 GMT
#6 2.681 server: gunicorn
#6 2.681 status: 401
#6 2.681 strict-transport-security: max-age=15552000
#6 2.681 vary: Accept
#6 2.681 x-content-type-options: nosniff
#6 2.681 x-frame-options: SAMEORIGIN
#6 2.681 x-launchpad-revision: 1a64fbf0a633b6c807613475aecca0f26ff240b3
#6 2.681 x-lazr-notifications: []
#6 2.681 x-powered-by: Zope (www.zope.org), Python (www.python.org)
#6 2.681 x-request-id: a401f90f-3f89-4634-b5e2-ba0b243f16d8
#6 2.681 x-vcs-revision: 1a64fbf0a633b6c807613475aecca0f26ff240b3
#6 2.681 x-xss-protection: 1; mode=block
#6 2.681 ---
#6 2.681 Response body:
#6 2.681 ---
#6 2.681 b"(<Archive object>, 'getSigningKeyData', 'launchpad.SubscriberView')"
#6 2.681 ---
#6 2.681 
------
executor failed running [/bin/sh -c add-apt-repository --yes ppa:stebbins/handbrake-releases]: exit code: 1
```

**Comment by pooshonbanerjee** [comment]
I tried another method to install Handbrake manually, installed fine but the NPM module cannot find HandbrakeCLI. I tried first by installing HandBrakeCLI only using `RUN flatpak install /app/cli/HandBrakeCLI-1.6.1-x86_64.flatpak -y`. You can see the commented line in Dockefile.

Then when that didn't work, I tried to install full HandBrake, got the same error.

### Dockerfile
```
# Use an official Node.js runtime as a parent image
FROM ubuntu:latest


# Set the working directory to /app
WORKDIR /app

COPY cli /app/cli

RUN apt-get update && \
    apt-get install -y flatpak && \
    flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

# RUN flatpak install /app/cli/HandBrakeCLI-1.6.1-x86_64.flatpak -y
RUN flatpak install /app/cli/HandBrake-1.6.1-x86_64.flatpak -y

# RUN Handbrake --version
# Copy the current directory contents into the container at /app
COPY . /app

# Install node

RUN apt-get update && \
    apt-get install -y curl && \
    curl -sL https://deb.nodesource.com/setup_18.x | bash - && \
    apt-get install -y nodejs

# Install any needed packages specified in package.json
RUN npm install

# Make port 3000 available to the world outside this container
EXPOSE 3000

# Define environment variable
# ENV NODE_ENV=production

# Run the app when the container launches
CMD ["npm", "start"]
```

### Error
```
2023-06-23 13:29:25 Server started on port 3000
2023-06-23 13:29:49 AI for business elevator pitch_Yumi Kim.mp4
2023-06-23 13:29:49 base64Name:  QUkgZm9yIGJ1c2luZXNzIGVsZXZhdG9yIHBpdGNoX1l1bWkgS2ltLm1wNA==
2023-06-23 13:29:49 {
2023-06-23 13:29:49   path: 'uploads/QUkgZm9yIGJ1c2luZXNzIGVsZXZhdG9yIHBpdGNoX1l1bWkgS2ltLm1wNA==/AI for business elevator pitch_Yumi Kim.mp4'
2023-06-23 13:29:49 }
2023-06-23 13:29:49 error:  HandbrakeCLINotFound: HandbrakeCLI application not found: HandBrakeCLI. Linux users must install HandbrakeCLI manually, please see https://handbrake.fr/downloads.php.
2023-06-23 13:29:49     at Handbrake._run (/app/node_modules/handbrake-js/dist/index.cjs:208:15)
2023-06-23 13:29:49     at /app/node_modules/handbrake-js/dist/index.cjs:599:17
2023-06-23 13:29:49     at process.processTicksAndRejections (node:internal/process/task_queues:77:11) {
2023-06-23 13:29:49   errno: -2,
2023-06-23 13:29:49   HandbrakeCLIPath: 'HandBrakeCLI',
2023-06-23 13:29:49   spawnmessage: 'spawn HandBrakeCLI ENOENT',
2023-06-23 13:29:49   output: '',
2023-06-23 13:29:49   options: {
2023-06-23 13:29:49     input: 'uploads/QUkgZm9yIGJ1c2luZXNzIGVsZXZhdG9yIHBpdGNoX1l1bWkgS2ltLm1wNA==/AI for business elevator pitch_Yumi Kim.mp4',
2023-06-23 13:29:49     output: 'uploads/QUkgZm9yIGJ1c2luZXNzIGVsZXZhdG9yIHBpdGNoX1l1bWkgS2ltLm1wNA==/AI for business elevator pitch_Yumi Kim_HB.mp4',
2023-06-23 13:29:49     preset: 'Very Fast 1080p30'
2023-06-23 13:29:49   }
2023-06-23 13:29:49 }
2023-06-23 13:29:49 encoding complete
2023-06-23 13:29:49 File deleted!
```

**Comment by pooshonbanerjee** [comment]
Then I went into my docker terminal, and tried to install manually.

### Install log
```
# flatpak install /app/cli/HandBrakeCLI-1.6.1-x86_64.flatpak 
Required runtime for fr.handbrake.HandBrakeCLI/x86_64/stable (runtime/org.freedesktop.Platform/x86_64/21.08) found in remote flathub
Do you want to install it? [Y/n]: Y

fr.handbrake.HandBrakeCLI permissions:
    dri   file access [1]

    [1] host


        ID                                         Arch          Branch        Op        Remote                     Download
        ID                                         Arch          Branch        Op        Remote                     Download
 1. [?] org.freedesktop.Platform.GL.default        x86_64        21.08         i         flathub                    129.5?MB / 129.8?MB
 2. [?] org.freedesktop.Platform.Locale            x86_64        21.08         i         flathub                     47.0?MB / 326.7?MB
        ID                                         Arch          Branch        Op        Remote                     Download
 1. [?] org.freedesktop.Platform.GL.default        x86_64        21.08         i         flathub                    129.5?MB / 129.8?MB
 2. [?] org.freedesktop.Platform.Locale            x86_64        21.08         i         flathub                     47.0?MB / 326.7?MB
 3. [?] org.freedesktop.Platform.openh264          x86_64        2.0           i         flathub                      1.5?MB / 1.5?MB
 4. [?] org.freedesktop.Platform                   x86_64        21.08         i         flathub                    185.9?MB / 201.6?MB
 5. [?] fr.handbrake.HandBrakeCLI                  x86_64        stable        i         handbrakecli-origin        0 bytes

Warning: While trying to apply extra data: apply_extra script failed, exit status 256
Installation complete.
```
But same error

`error:  HandbrakeCLINotFound: HandbrakeCLI application not found: HandBrakeCLI. Linux users must install HandbrakeCLI manually, please see https://handbrake.fr/downloads.php.`

**Comment by pooshonbanerjee** [comment]
No I didn't. Wasted a lot of time first with Handbrake then with ffmpeg but
couldn't install inside a docker container.

Regards

**Comment by FlawaCLV** [comment]
@pooshonbanerjee I actually made it work using this DockerFile and [Fluent ffmpeg-API for node.js](https://www.npmjs.com/package/fluent-ffmpeg)

```DockerFile
FROM node:18.12-alpine

RUN apk add ffmpeg

WORKDIR /usr/src/api

COPY package*.json ./
RUN npm install --legacy-peer-deps

COPY . .
RUN npm run build

ENV ENV production
ENV PORT 8080
ENV HOST 0.0.0.0

EXPOSE $PORT

CMD npm start
```

**Comment by pooshonbanerjee** [comment]
Cool, I'll check it out.

**Comment by 75lb** [comment]
Regarding the HandbrakeCLI not being found, you can [set a custom path via the API or with an environment variable](https://github.com/75lb/handbrake-js?tab=readme-ov-file#handbrakecli-path).

**Comment by 75lb** [comment]
Closing. If [specifying a custom HandbrakeCLI path](https://github.com/75lb/handbrake-js?tab=readme-ov-file#handbrakecli-path) does not work, let me know.
